# Generated by Django 2.1.1 on 2018-09-02 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_kot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kot',
            name='balance',
        ),
    ]
