# Generated by Django 2.1.1 on 2018-09-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_kot_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
