# Generated by Django 2.1.1 on 2018-09-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20180902_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='positive',
            field=models.BooleanField(default=False),
        ),
    ]
