# Generated by Django 2.1.1 on 2018-09-02 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_expense_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
