# Generated by Django 2.1.1 on 2018-09-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supper', '0002_day_week'),
        ('bank', '0006_auto_20180902_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supper.Day'),
        ),
    ]
